language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qq
  - curl http://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  - echo "deb http://nginx.org/packages/ubuntu/ precise nginx" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://nginx.org/packages/ubuntu/ precise nginx" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install nginx
  - sudo nginx -s stop
  - npm install -g grunt-cli
  - echo "$TRAVIS_BUILD_DIR"
  - echo "$SAUCE_USERNAME"
  - cd test/sauce && npm install
  - node launch_connect.js &
  - $TRAVIS_BUILD_DIR/test/sauce/wait_for_browser_provider.sh
  - cd $TRAVIS_BUILD_DIR
before_script:
  - "cp test/travis/config-travis.js src/js/config.js"
  - "cp test/travis/ripple-travis.txt ripple.txt"
  - npm install -g se-interpreter
  - ls -l "$TRAVIS_BUILD_DIR"
  - cat "$TRAVIS_BUILD_DIR/test/travis/nginx.conf"
  - sudo nginx -c "$TRAVIS_BUILD_DIR/test/travis/nginx.conf"
  - curl -i http://localhost:9002
  - curl -i http://localhost:9002/
  - sudo ps aux
  - sudo ls -l /proc/*/exe || true
script:
  - se-interpreter test/selenium/interpreter_config.json
  - cd cmd && npm install
  - ls -l
  - node rcmd.js
after_script:
  - echo "nginx/error:"
  - sudo cat /var/log/nginx/error.log
  - echo "nginx/access:"
  - sudo cat /var/log/nginx/access.log
  - echo "config.js:"
  - curl http://localhost:9001/config.js
  - echo "ripple.txt:"
  - curl http://localhost:9001/ripple.txt
  - curl http://localhost:9001/ripple.txt
env:
  global: 
    - SAUCE_CONNECT_VERSION=4.3.6
    - SAUCE_USERNAME=tonga
    - SAUCE_ACCESS_KEY=1553f141-1258-4319-b20d-7743def99fbb


